#33 jesse
lderkzen/SOPROJ11Q pull request #23
Opened 2021-04-18 17:33 UTC by Stupers

Zorgt ervoor dat de custom messages werken.

2021-04-18 17:42 UTC, Ghoster524 approved these changes

2021-04-19 14:54 UTC, imfi-jz requested changes
Ik krijg helaas geen custom messages te zien als ik pauzeer of beëindig. De eerste keer dat ik een spel startte kreeg ik daar wel een schermpje van met tekst, maar de andere keren dat ik een game startte niet.

2021-04-19 15:13 UTC, Ghoster524 approved these changes
Bij mij lijkt het wel te werken! Met game 1 en game 2

2021-04-19 15:56 UTC, lderkzen reviewed
Alvast comments

2021-04-19 15:56 UTC, lderkzen commented on app/Http/Controllers/GameController.php
> +use OutOfBoundsException;
Wordt deze wel gebruikt?

2021-04-19 16:08 UTC, lderkzen approved these changes

2021-04-19 19:46 UTC, imfi-jz approved these changes
big toppie

2021-04-19 19:47 UTC, merged