User Story 50
lderkzen/SOPROJ11Q pull request #31
Opened 2021-05-02 15:01 UTC by LeonNiekus

Draft PR voor User Story 50

Alle veranderingen binnen deze PR zijn terug te vinden onder het game overview scherm (wanneer je op spel starten hebt geklikt dus).

TL;DR: een tweede kaart in de website met verschillende pins erop welke verschillende items voorstellen (met een mousehover om je te vertellen wat alles is)

2021-05-02 15:07 UTC, Ghoster524 commented
Ziet er netjes uit!

2021-05-04 16:39 UTC, lderkzen submitted a review, later dismissed

2021-05-04 17:21 UTC, lderkzen submitted a review, later dismissed

2021-05-04 20:02 UTC, Ghoster524 approved these changes

2021-05-04 20:26 UTC, Ghoster524 requested changes
De data die met de socket wordt teruggestuurd is niet meer correct. Eerst werd er simpel een `message` teruggestuurd, maar nu komt een object terug zonder een bericht.

Hoe de data eerst terugkwam:
![image](https://user-images.githubusercontent.com/60692171/117065193-7698fe80-ad27-11eb-96bf-2649116b4c20.png)

Hoe de data nu terugkomt:
![image](https://user-images.githubusercontent.com/60692171/117065358-b4962280-ad27-11eb-80ed-a58af9f6fa8c.png)

Ik heb de laatste versie van deze branch binnengehaald. Daarna ging ik het spel pauzeren, maar toen bleek er niks worden weergeven. Toen had ik dev er weer bij gepakt, maar daar wordt het wel in teruggegeven. Dus er lijkt echt iets te zijn verandert met de `message`.

2021-05-05 11:27 UTC, lderkzen submitted a review, later dismissed

2021-05-05 12:30 UTC, Ghoster524 submitted a review, later dismissed

2021-05-05 13:07 UTC, imfi-jz approved these changes

2021-05-05 14:51 UTC, Stupers approved these changes

2021-05-05 15:48 UTC, merged