US 25 - Scores in database and required end-points
lderkzen/SOPROJ11Q pull request #33
Opened 2021-05-02 19:24 UTC by imfi-jz

Boef en politie scores in database en end-points voor verwijderen van loot, updaten van score en ophalen van invite keys van game.

Deze hoort bij [de mobile PR voor US 25](https://github.com/imfi-jz/SOPROJ11Q-Mobile/pull/40).

2021-05-03 11:54 UTC, LeonNiekus submitted a review, later dismissed
Het werkt op zich allemaal goed. Het enige ding dat ik persoonlijk aan zou passen is dat de PATCH en DELETE routes iets zouden kunnen returnen nadat ze klaar zijn met hun acties. Dit kan dan een bericht zijn als 'Success' of het object zelf (dus return $game; o.i.d.)

2021-05-03 13:11 UTC, imfi-jz commented
> Het werkt op zich allemaal goed. Het enige ding dat ik persoonlijk aan zou passen is dat de PATCH en DELETE routes iets zouden kunnen returnen nadat ze klaar zijn met hun acties. Dit kan dan een bericht zijn als 'Success' of het object zelf (dus return $game; o.i.d.)

De $game returnen lijkt mij ook een goeie, maar een success message bij delete lijkt me niet nodig. Er kan in de app al gecheckt worden of het verzoek gelukt is of niet (volgens mij d.m.v. de status code). En een verwijderd object returnen lijkt me ook niet ideaal.

2021-05-03 13:14 UTC, LeonNiekus commented
> > Het werkt op zich allemaal goed. Het enige ding dat ik persoonlijk aan zou passen is dat de PATCH en DELETE routes iets zouden kunnen returnen nadat ze klaar zijn met hun acties. Dit kan dan een bericht zijn als 'Success' of het object zelf (dus return $game; o.i.d.)
> 
> De $game returnen lijkt mij ook een goeie, maar een success message bij delete lijkt me niet nodig. Er kan in de app al gecheckt worden of het verzoek gelukt is of niet (volgens mij d.m.v. de status code). En een verwijderd object returnen lijkt me ook niet ideaal.

Daar ben ik het mee eens

2021-05-03 14:41 UTC, LeonNiekus submitted a review, later dismissed

2021-05-03 17:36 UTC, lderkzen requested changes

2021-05-03 17:36 UTC, lderkzen commented on app/Http/Requests/UpdateThievesScoreRequest.php
> +class UpdateThievesScoreRequest extends FormRequest
Is deze nog wel nodig?

2021-05-03 17:36 UTC, lderkzen commented on routes/api.php
> +    $router->delete('/loots/{loot}', [LootController::class, 'destroy']);
'/loot' zou wat mooier zijn i.p.v. '/loots'

2021-05-04 10:21 UTC, LeonNiekus submitted a review, later dismissed

2021-05-04 14:51 UTC, LeonNiekus approved these changes

2021-05-04 14:53 UTC, lderkzen approved these changes

2021-05-04 14:53 UTC, merged