New feature: Game Presets
lderkzen/SOPROJ11Q pull request #43
Opened 2021-05-12 01:00 UTC by lderkzen

- [ ] The database can store Presets
- [ ] Presets can also remember BorderMarkers & Loot
- [ ] Interface to store Presets
- [ ] Interface to load Presets

Aside from the new feature I have also done a minor overhaul to the database. BorderMarkers and Loot now have polymorphic relationships so that they can reference and be referenced by Game and GamePreset. The relationship between Game and Loot is also no longer a many-to-many but a one-to-many as we were already using it like a one-to-many relationship anyways.

2021-05-15 09:55 UTC, LeonNiekus approved these changes

2021-05-15 09:58 UTC, LeonNiekus submitted a review, later dismissed

2021-05-15 10:43 UTC, imfi-jz requested changes
Als ik een template opsla met een logo staat er "The given data was invalid", terwijl Start Game dan wel werkt. En als ik de kleur wijzig wordt nog steeds de standaard kleur (#0099ff) opgeslagen in de database.

2021-05-16 14:09 UTC, LeonNiekus approved these changes

2021-05-16 19:33 UTC, LeonNiekus submitted a review, later dismissed

2021-05-17 12:43 UTC, imfi-jz submitted a review, later dismissed

2021-05-18 13:11 UTC, LeonNiekus approved these changes

2021-05-18 13:30 UTC, Stupers approved these changes

2021-05-18 13:45 UTC, merged